TG-26 setup retrofit, AuthorizationInterceptor and hilt
2Up-Chapter-Android/2up-finance pull request #20
Opened 2023-03-07 03:13 UTC by YuuHaruna

## Description & Motivation
Setup Retrofit and Authorization Interceptor so that app can connect to Back-End. Setup Hilt for Dependencies Injection

## Ticket number and links

[Task 26 on taiga](https://tree.taiga.io/project/vanlinh999-2up-personal-finance/task/26)

## Screenshots

## Checklist

- [x] I have reviewed my own code
- [x] I have verified that my commits are properly labelled
- [x] I have updated any related documentation
- [x] I have added appropriate tests for my new changes
- [x] I have updated any existing tests related to my changes

2023-03-07 05:10 UTC, linhvnguyen9 requested changes

2023-03-07 05:10 UTC, linhvnguyen9 commented on app/src/main/java/com/track/finance2up/Finance2UpApplication.kt
> +        Hawk.init(applicationContext).build()
a nghĩ có thể tách thành hàm như kiểu `setupHawk()` giống thằng Timber, sẽ dễ đọc hơn chút

2023-03-07 05:10 UTC, linhvnguyen9 commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
permission này đã bao hàm permission INTERNET chưa nhỉ? Liệu h call API để permission này ko có bị crash ko e? :))))

2023-03-07 05:10 UTC, linhvnguyen9 commented on app/build.gradle
> +    implementation AndroidLibraries.hawk
còn 1 cái tích hợp navigation compose + hilt. Tiện e thêm cả cái thư viện tích hợp 2 cái luôn nhé.
https://developer.android.com/jetpack/compose/libraries#hilt-navigation

2023-03-07 05:10 UTC, linhvnguyen9 commented on buildSrc/src/main/java/Dependencies.kt
> +    const val retrofitConverter = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
e nghĩ sao nếu đổi thành `retrofitGsonConverter`? Vì retrofit cũng có khá nhiều loại converter khác nhau, đặt vậy a nghĩ rõ hơn chút

2023-03-07 05:10 UTC, linhvnguyen9 commented on buildSrc/src/main/java/Dependencies.kt
> +    const val loggingIntercepter = "com.squareup.okhttp3:logging-interceptor:${Versions.loggingIntercepter}"
optional (from cảnh sát chính tả 😆): `loggingIntercepter` -> `loggingInterceptor`

2023-03-07 05:10 UTC, linhvnguyen9 commented on buildSrc/src/main/java/Dependencies.kt
> +    const val loggingIntercepter = "4.10.0"
optional (from cảnh sát chính tả 😆): loggingIntercepter -> loggingInterceptor

2023-03-07 05:10 UTC, linhvnguyen9 commented on common/src/main/java/com/aibles/finance/AppDispatchers.kt
> +)
ngon e! có phần này về sau làm unit test khá dễ

2023-03-07 05:10 UTC, linhvnguyen9 commented on common/src/main/java/com/aibles/finance/ListMapper.kt
> +        }
phần list mapper này trước a nghĩ ra, nhưng có vẻ cũng khá cồng kềnh. A nghĩ hàm mapper có thể đổi thành extension fun, đặt trong package data/mapper

2023-03-07 05:10 UTC, linhvnguyen9 commented on common/src/main/java/com/aibles/finance/constpackage/HawkKey.kt
> +package com.aibles.finance.constpackage
phần constpackage a nghĩ ko hay lắm, nên đặt cùng với file xử lý Hawk. Phần gọi đến Hawk tốt hơn hết là xử lý trong 1 file, kiểu như

```
object HawkDataSource {
    fun getAccessToken(): String { ... }
    fun saveAccessToken(token: String)  { ... }
    
    companion object {
        private const val ACCESS_TOKEN = "ACCESS_TOKEN"
    }
}
```

2023-03-07 05:10 UTC, linhvnguyen9 commented on common/src/main/java/com/aibles/finance/constpackage/SharedPrefKey.kt
> +}
same comment như trên

2023-03-07 05:10 UTC, linhvnguyen9 commented on common/src/main/java/com/aibles/finance/data/remote/services/CommonService.kt
> +    suspend fun refreshToken(@Body refreshTokenRequest: RefreshTokenRequest): Resource<String>
phần này e đã check lại backend là mình có refreshToken chưa?

2023-03-07 05:10 UTC, linhvnguyen9 commented on common/src/main/java/com/aibles/finance/data/remote/util/BaseErrorResponse.kt
> +)
cùng câu hỏi, em check lại với BE phần này chưa? Nếu r thì oke nhé

2023-03-07 05:10 UTC, linhvnguyen9 commented on common/src/main/java/com/aibles/finance/data/remote/util/HeaderAuthorizationInterceptor.kt
> +        val headers = request.headers.newBuilder().add("authorization", jwt ?: "null").build()
a ko nhớ rõ phần này lắm. Ko biết BE đang yêu cầu auth dạng nào nhỉ? Nếu JWT thì hình như phải thêm "Bearer". Check lại với BE nhé e

2023-03-07 05:10 UTC, linhvnguyen9 commented on common/src/main/java/com/aibles/finance/data/repository/CommonRepositoryImpl.kt
> +    }
same comment phần trên. Check lại BE xem họ có làm refresh ko nhé? Nếu có thì oke

2023-03-07 05:10 UTC, linhvnguyen9 commented on common/src/main/java/com/aibles/finance/di/CommonModule.kt
> +            .baseUrl(BASE_URL)
phần này thử ngâm cứu đặt base URL vào trong file manifest/ build.gradle nhé. Để về sau mình có thể đổi giữa nhiều môi trường khác nhau

2023-03-07 05:10 UTC, linhvnguyen9 commented on common/src/main/java/com/aibles/finance/di/CommonModule.kt
> +package com.aibles.finance.di
e nghĩ sao nếu mình để các Module vào cùng package với layer của nó?

chẳng hạn như những thứ liên quan đến layer data thì quẳng vào `com.aibles.finance.feature.home.data.di`

cc @JKhanh

2023-03-07 05:10 UTC, linhvnguyen9 commented on common/src/main/java/com/aibles/finance/dto/LocalDto.kt
> +}
same comment với phần mapper ở trên. A nghĩ có thể cân nhắc bỏ phần này đi

2023-03-07 05:10 UTC, linhvnguyen9 commented on common/src/main/java/com/aibles/finance/dto/RemoteDto.kt
> +}
same comment phần mapper

2023-03-07 05:10 UTC, linhvnguyen9 commented on common/src/main/java/com/aibles/finance/presentation/utils/ResourcesProvider.kt
> +    fun getDrawable(@DrawableRes drawableResId: Int): Drawable?{
```suggestion
    fun getDrawable(@DrawableRes drawableResId: Int): Drawable? {
```

2023-03-07 05:10 UTC, linhvnguyen9 commented on common/src/main/java/com/aibles/finance/utils/ActivityExtension.kt
> +}
bên compose có hàm ẩn keyboard ngắn hơn, a nghĩ phần này có thể bỏ

2023-03-07 14:44 UTC, YuuHaruna commented on buildSrc/src/main/java/Dependencies.kt
> +    const val loggingIntercepter = "com.squareup.okhttp3:logging-interceptor:${Versions.loggingIntercepter}"
:))))))))))

2023-03-07 14:45 UTC, DawnHNguyen commented on common/src/main/java/com/aibles/finance/data/remote/services/CommonService.kt
> +    suspend fun refreshToken(@Body refreshTokenRequest: RefreshTokenRequest): Resource<String>
Em tiện tay cứ setup trước, nếu có thì mình dùng luôn, không thì xoá đi thôi ạ

2023-03-07 14:46 UTC, YuuHaruna commented on common/src/main/java/com/aibles/finance/data/remote/util/BaseErrorResponse.kt
> +)
Cũng như trên, em dựng sẵn cái base này, khi nào có docs từ BE em chỉ cần sửa lại 1 tý là được

2023-03-07 14:46 UTC, YuuHaruna commented on common/src/main/java/com/aibles/finance/data/remote/util/HeaderAuthorizationInterceptor.kt
> +        val headers = request.headers.newBuilder().add("authorization", jwt ?: "null").build()
Vâng ạ, khi nào có docs cụ thể từ BE em sẽ bổ sung vào ạ

2023-03-09 00:26 UTC, linhvnguyen9 approved these changes
có vẻ ngon r đó e. Check nốt phần default arg khi get string trong Hawk là đc

2023-03-09 00:26 UTC, linhvnguyen9 commented on common/src/main/java/com/aibles/finance/data/local/HawkDataSource.kt
> +    fun getAccessToken(): String = Hawk.get(HawkKey.ACCESS_TOKEN, "null")
a chưa hiểu giá trị default đoạn này lắm. Liệu mình trả về 1 xâu rỗng đc ko hay phải trả về string null?

2023-03-09 00:26 UTC, linhvnguyen9 commented on common/src/main/java/com/aibles/finance/data/repository/CommonRepositoryImpl.kt
> +        if (refreshTokenResponse.isSuccessful()) HawkDataSource.saveAccessToken(refreshTokenResponse.data ?: "null")
same comment

2023-03-09 13:22 UTC, DawnHNguyen commented on common/src/main/java/com/aibles/finance/data/local/HawkDataSource.kt
> +    fun getAccessToken(): String = Hawk.get(HawkKey.ACCESS_TOKEN, "null")
Cái này nhằm mục đích debug dễ hơn thôi ạ, để khi đọc log nhận thấy chữ null trong okhttp logging sẽ dễ nhận ra hơn

2023-03-09 13:25 UTC, merged