TG-37: code screen register complete
2Up-Chapter-Android/2up-finance pull request #32
Opened 2023-04-13 14:41 UTC by ductamisme

## Description & Motivation
because I made a mistake that broke the code in the [TG-37] code register, so I created this task instead

## Ticket number and links

## Screenshots

## Checklist

- [ ] I have reviewed my own code
- [ ] I have verified that my commits are properly labelled
- [ ] I have updated any related documentation
- [ ] I have added appropriate tests for my new changes
- [ ] I have updated any existing tests related to my changes

2023-04-13 15:15 UTC, YuuHaruna requested changes

2023-04-13 15:15 UTC, DawnHNguyen commented on feature/authentication/src/main/java/com/finance2up/authentication/presentation/ui/register/RegisterScreen.kt
> +        navController.navigate("LoginScreen")
Theo đúng flow thì nó sẽ nav sang bên OTP chú không phải là Login nhé. Với check lại xem, theo anh biết thì code kiểu này sẽ nav vô hạn, màn hình nháy nháy liên tục chứ nó sẽ không nav cái rồi dừng đâu

2023-04-13 15:15 UTC, DawnHNguyen commented on feature/authentication/src/main/java/com/finance2up/authentication/presentation/ui/register/RegisterScreen.kt
> +                    keyboardType = KeyboardType.Text,
Mặc định đã là KeyboardType.Text rồi, em có thể không cần viết cái này

2023-04-13 15:15 UTC, YuuHaruna commented on feature/authentication/src/main/java/com/finance2up/authentication/presentation/ui/register/RegisterScreen.kt
> +                    keyboardType = KeyboardType.Text,
Như trên

2023-04-13 15:15 UTC, YuuHaruna commented on feature/authentication/src/main/java/com/finance2up/authentication/presentation/ui/register/RegisterScreen.kt
> +                                .size(100.dp)
sao tự nhiên lại bỏ dimen resource thế em

2023-04-13 15:15 UTC, DawnHNguyen commented on feature/authentication/src/main/java/com/finance2up/authentication/presentation/ui/register/RegisterScreen.kt
> +                    append("")
Em append string rỗng này để làm gì nhỉ, nó có ý nghĩa gì đâu

2023-04-16 08:53 UTC, ductamisme commented on feature/authentication/src/main/java/com/finance2up/authentication/presentation/ui/register/RegisterScreen.kt
> +        navController.navigate("LoginScreen")
dạ vâng ạ e có nó nháy liên tục thì cái này trông hay thật ạ :))

2023-04-16 08:58 UTC, ductamisme commented on feature/authentication/src/main/java/com/finance2up/authentication/presentation/ui/register/RegisterScreen.kt
> +                    keyboardType = KeyboardType.Text,
dạ vâng ạ nó mặc định thế thật nhưng mà e có để bên dưới là keyboardType làm tham số truyền vào thì để phân loại nó với email và usernam, fullname. nếu kéo xuống thì e có để cái keyboardType của email là     keyboardType = KeyboardType.Email ạ

2023-04-16 08:58 UTC, ductamisme commented on feature/authentication/src/main/java/com/finance2up/authentication/presentation/ui/register/RegisterScreen.kt
> +                    keyboardType = KeyboardType.Text,
e có để comment ở bên trên rồi ạ

2023-04-16 10:52 UTC, ductamisme commented on feature/authentication/src/main/java/com/finance2up/authentication/presentation/ui/register/RegisterScreen.kt
> +                                .size(100.dp)
e có chỉnh một chút ui/ux ạ lúc trước trông nó đần quá ạ :))

2023-04-17 08:12 UTC, YuuHaruna commented on feature/authentication/src/main/java/com/finance2up/authentication/presentation/ui/register/RegisterScreen.kt
> +                    keyboardType = KeyboardType.Text,
Vậy em có thể set tham số mặc định, để em đỡ phải truyền vào (đây là cmt optional mang tính nhắc nhở, cân nhắc sau này có thể làm theo).

2023-04-17 08:12 UTC, YuuHaruna commented on feature/authentication/src/main/java/com/finance2up/authentication/presentation/ui/register/RegisterScreen.kt
> +                                .size(100.dp)
Nếu chỉnh thì nên chỉnh trong dimens.xml, chứ không phải ở đây. Đó là mục đích của việc tạo ra file dimens.xml và tách các resource ra mà. Nếu em làm như này thì thà không tách file làm gì cho đỡ mệt. Đoạn trên cũng có giá trị hard code mà không tách dimen đó, để ý nha

2023-04-17 08:17 UTC, ductamisme commented on feature/authentication/src/main/java/com/finance2up/authentication/presentation/ui/register/RegisterScreen.kt
> +                                .size(100.dp)
vâng ạ đúng rồi ạ e không để ý mà hard code ạ

2023-04-17 08:17 UTC, ductamisme commented on feature/authentication/src/main/java/com/finance2up/authentication/presentation/ui/register/RegisterScreen.kt
> +                    keyboardType = KeyboardType.Text,
dạ vâng ạ

2023-04-17 08:20 UTC, YuuHaruna approved these changes

2023-04-17 08:20 UTC, merged